name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Repo
         uses: actions/checkout@master

       - name: Brotli compress the html, css and js files in the "build" directory
         id: brotli
         uses: charlesworth/compress-action@1.0
         with:
           target-directory: 'build'
