name: Minify Action
on: push

jobs:
  build:
    name: Minify files
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@master
        with:
          directory: 'build'
